name: silence
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  fluro: "^1.3.5"
  http: ^0.12.0+2
  provider: ^3.1.0+1
  shared_preferences: 0.5.4+3
  dio: "^3.0.4"
  dio_cookie_manager: "^1.0.0"
  cookie_jar: ^1.0.0
  path_provider: ^1.4.0
  # audioplayers: ^0.13.2
  # audioplayer: ^0.5.2
  percent_indicator: "^2.1.1"
  cupertino_icons: ^0.1.2
  # flutter_statusbar_manager : ^1.0.2
  # indexed_list_view: ^1.0.8
  # infinite_listview: ^1.0.1+1
  # audio_focus: ^0.0.1
  flutter_launcher_icons: "^0.7.3"
  flutter_exoplayer: ^0.5.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/


flutter_native_splash:
  image: assets/images/new_splash.png
  color: "42a5f5"
# flutter pub pub run flutter_native_splash:create

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
# flutter pub run flutter_launcher_icons:main